name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Update commit hash in menu.yaml
        run: |
          COMMIT_HASH=$(git rev-parse --short=8 HEAD)
          echo "Updating branch to commit hash: $COMMIT_HASH"
          node -e "
            const fs = require('fs');
            const yaml = require('js-yaml');
            const path = 'src/config/menu.yaml';
            const content = fs.readFileSync(path, 'utf8');
            const config = yaml.load(content);
            if (config?.settings?.github) {
              config.settings.github.branch = '$COMMIT_HASH';
              fs.writeFileSync(path, yaml.dump(config, {indent: 2, lineWidth: -1, quotingType: '\"', forceQuotes: false}));
              console.log('✅ Updated GitHub branch to: $COMMIT_HASH');
            }
          "

      - name: Build
        run: npm run build

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true